version: '3.7'

services:
   client:
    build: 
      context: .
    volumes:
      - .:/zamdaa_page
    stdin_open: true  
    ports: 
      - "3000:3000"
    image: client:zamdaa
    container_name: zamdaa_container
    command: npm start